### PR TITLE
Update set of available tool versions

### PR DESCRIPTION
**Pull request by seh**
Introduce [_kustomize_ version 5.0.2](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize/v5.0.2), and make that the default version. Remove version 4.5.5.

Accommodate kubernetes-sigs/kustomize#4999 by relocating the extracted Helm chart in the unit test data, placing the directory one level deeper within a new containing directory distinguishing the files for each version.

Introduce [Helm version 3.11.3](https://github.com/helm/helm/releases/tag/v3.11.3), and make that the default version. Remove version 3.9.2.

### CODE REVIEW

**Comment by Mitsuwa** [comment]
Perhaps while you are here you can update the bazelversion to `6.1.1`

**Review by Mitsuwa — APPROVED** [review]
builds for me

**Comment by seh** [comment]
> Perhaps while you are here you can update the bazelversion to `6.1.1`

I'll do that the next time through, which will likely be for the next Helm release for which they've published [a candidate](https://github.com/helm/helm/releases/tag/v3.12.0-rc.1).

**Comment by seh** [comment]
See #14 for the next update.

**Pull request merged**
